# Generated by Django 5.1.6 on 2025-02-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoriaa',
        ),
    ]
