# Generated by Django 5.1.6 on 2025-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_fornecedores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='nome',
            new_name='CNPJ',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='Contato',
            field=models.CharField(blank='False', max_length=200, null='False', verbose_name='Contato'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='Nome',
            field=models.CharField(blank='False', max_length=200, null='False', verbose_name='Nome'),
            preserve_default='False',
        ),
    ]
