# Generated by Django 5.1.6 on 2025-02-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_nome_fornecedores_cnpj_fornecedores_contato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='CNPJ',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='Contato',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='fornecedores',
            old_name='Nome',
            new_name='nome',
        ),
    ]
